### ISSUE TITLE
Can it keep downloading?

### ISSUE THREAD

**Issue by alexiskattan** [ostrolucky/Bulk-Bing-Image-downloader#15]
It stops after around 700 images.  Is there a way to make it keep going?

**Comment by ostrolucky** [comment]
It keeps going until it downloads all images

**Comment by jbohnslav** [comment]
I have also found that it stops after around ~700- 1000 images, despite many more potential images on the bing image page.

**Comment by ostrolucky** [comment]
Many of thoses are duplicate images that bbid detects and discards. Perhaps I could take a look if somebody provided reproducing steps.

**Comment by ParthMandaliya** [comment]
Hi, @jbohnslav I agree with @ostrolucky most of the images are duplicate images if you need more data you can download it from images.google.com with the help of https://github.com/hardikvasa/google-images-download, but if you use google-images-download it'll download duplicate images as well, you will have to spend more time cleaning your data.

I suggest you use this other script and download the data from google and implement the logic the same as bbid to remove duplicate image issue, I believe it'll not take much of your time to implement the logic.
