### ISSUE TITLE
Program not working any more?

### ISSUE THREAD

**Issue by i-akbari** [ostrolucky/Bulk-Bing-Image-downloader#17]
**when I ran the program it gives me error:**

> Traceback (most recent call last):
>   File "./bbid.py", line 118, in <module>
>     fetch_images_from_keyword(args.search_string,output_dir)
>   File "./bbid.py", line 60, in fetch_images_from_keyword
>     response=urllib.request.urlopen(request)
>   File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.4/urllib/request.py", line 469, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.4/urllib/request.py", line 507, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found

What's the problem?

**Comment by ostrolucky** [comment]
Still works for me. Maybe temporary bing outage?

**Comment by i-akbari** [comment]
@ostrolucky Thank you for your reply. I noticed that the problem was related to bing (or CDN) SSL certificate. 
The program is OK.
