### ISSUE TITLE
Only around 40 queries could be downloaded

### ISSUE THREAD

**Issue by rayjs** [ostrolucky/Bulk-Bing-Image-downloader#19]
Hi,
I have a query file with a lot of queries but it seems every time I run it, it only downloads the first ~40 queries. I dived into the code but did not see any such check. Could you please help. Thank you.

The only flag I use is: 
--limit=200
and bingcount=35.

Everything else is as is provided.

**Comment by ostrolucky** [comment]
There isn't such check. Bing itself must be affecting this.

**Comment by rayjs** [comment]
Thank you
