### ISSUE TITLE
Doesn't download more than 100 images!!

### ISSUE THREAD

**Issue by ParthMandaliya** [ostrolucky/Bulk-Bing-Image-downloader#25]
Hi,

I'm facing some issues here, this script is not downloading images more than 100, I think that's because of the no web driver specified (like while using selenium we use chromedriver) if you have updated script, can you please upload? I'm proving an input file it also doesn't traverse through the entire input file, at a random point the script exits (without any error).

Thanks Man, you saved a lot of my time writing a new script.

**Comment by ostrolucky** [comment]
Can you share command line you used so I can reproduce? Also not sure what you mean with web driver

**Comment by ParthMandaliya** [comment]
By web driver, I mean when we use selenium library to perform scrapping we need to provide chromedriver to it. but you are only using urllib here, maybe something like that can be provided here for urllib as well?

python bbid.py -f ./birds_name_bbid_new -o ~/dataset/images_bbid/  --limit 950

here is the file birds_name_bbid_new...
https://drive.google.com/open?id=1QnIZC--d4JoWEJzcHIoOX0uSbJ3zE6ns

**Comment by ostrolucky** [comment]
It works for me. What OS do you use?

**Comment by ParthMandaliya** [comment]
Ubuntu 18.04

**Comment by ParthMandaliya** [comment]
Are you able to download more than 100 images?

**Comment by ostrolucky** [comment]
Yep. There is 4202 images. Please check exit code of command ( via `echo $?` after bbid finishes)

**Comment by ParthMandaliya** [comment]
I just ran the script again, it is not throwing any error but still, the exit code is 1 !!!

**Comment by ostrolucky** [comment]
Can you show me output of `ulimit -n`, afterwards increase this limit via `ulimit -n 1024` and see if it changes something for next command run?

**Comment by ParthMandaliya** [comment]
it's 1024

**Comment by ostrolucky** [comment]
Maybe you can also play with --threads option

**Comment by ParthMandaliya** [comment]
yes, but I do not have a very high-speed internet connection (although it's stable), that's why 20 is enough for me, I think.
On which OS, you test this script?

**Comment by ostrolucky** [comment]
I mean reduce it, not increase

**Comment by ParthMandaliya** [comment]
Surely, reducing the thread might help, will get back to you after the next run...

**Comment by ParthMandaliya** [comment]
Tried still the same issue...

**Comment by ostrolucky** [comment]
Have you also tried to use 1, or 2 threads only as well? If that doesn't make difference, perhaps use strace as a last resort to see what's going on.

**Comment by ParthMandaliya** [comment]
yes, I've used 1 thread as well, and now I'm thinking to change the script a little bit and include selenium and see how it works.

**Comment by ostrolucky** [comment]
selenium is very slow, but I guess in your case it would be better than just stopping entirely

**Comment by ParthMandaliya** [comment]
yes

**Comment by ostrolucky** [comment]
Related #15

I would need som help from somebody who can troubleshoot this. I can't fix it if I can't reproduce it

**Comment by ParthMandaliya** [comment]
surely, I'll help you to troubleshoot, I think you'll be able to reproduce it if you give the large keyword file and run the script once it ends, check the output directory it will neither download images for all the keywords mentioned in the input file nor create directories for all keywords.

you can use the input file I uploaded earlier to try to reproduce.

This weekend I'll try to debug, and see what's happening, and let you know. As of now, I didn't get the time to troubleshoot.

**Comment by ostrolucky** [comment]
I actually did use exact same file you posted here, with same CLI arguments and it downloads for me over 1000 images

**Comment by ParthMandaliya** [comment]
for all the keywords?

**Comment by ostrolucky** [comment]
Indeed, no. Can you try if increasing timeout on this line https://github.com/ostrolucky/Bulk-Bing-Image-downloader/blob/2c858cfb83818a642b11aa514c728d2c9dee528d/bbid.py#L77, eg. to 1 helps? Seems it does for me

**Comment by monajalal** [comment]
@ostrolucky how can I download 5000 images? It stops after 458 image downloads.

(base) mona@mona:~/research/Bulk-Bing-Image-downloader$ ./bbid.py -s "cat" -limit 2000
usage: bbid.py [-h] [-s SEARCH_STRING] [-f SEARCH_FILE] [-o OUTPUT]
               [--adult-filter-on] [--adult-filter-off] [--filters FILTERS]
               [--limit LIMIT] [--threads THREADS]
bbid.py: error: unrecognized arguments: -limit 2000

**Comment by monajalal** [comment]
@ostrolucky the script stops downloading after nearly 500 images even though I set the limit to 2000. Do you know how I can download more images?
(base) mona@mona:~/research/Bulk-Bing-Image-downloader$ ./bbid.py -s 'cat' --limit 2000

**Comment by ostrolucky** [comment]
You need to make sure there actually is more than 2000 unique images on bing first. After that, you might want to experiment with changing the sleep line of code I posted, it's a bing issue.
