### ISSUE TITLE
Error In Using Script

### ISSUE THREAD

**Issue by Skyferia** [ostrolucky/Bulk-Bing-Image-downloader#28]
Hi there,

My issue is the same as this: https://github.com/ostrolucky/Bulk-Bing-Image-downloader/issues/22
I've even changed IDE, and also tried reinstalling, but with the same outcome. 

Here's what happened (generally):
1. Opened _bbid.py_ with _IDLE IDE_
2. Ran it, and this showed up:
```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\<directory path here>\bbid.py
usage: bbid.py [-h] [-s SEARCH_STRING] [-f SEARCH_FILE] [-o OUTPUT]
               [--adult-filter-on] [--adult-filter-off] [--filters FILTERS]
               [--limit LIMIT] [--threads THREADS]
bbid.py: error: Provide Either search string or path to file containing search strings
```

3. Then tried these two:
```
>>> bbid.py -h
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    bbid.py -h
NameError: name 'bbid' is not defined
```
```
>>> bbid.py -s "dog"
SyntaxError: invalid syntax
```
>>> 

Can you please help identify the cause?

**Comment by ostrolucky** [comment]
> 1. Opened bbid.py with IDLE IDE

This step isn't correct, use normal cmd please. You are running python first and then trying to run the script, instead of running script through python. I've adjusted README, that should help you.

**Comment by Skyferia** [comment]
Thanks for the cmd pointer and the command line for _Windows_. 

Sadly, after that, these happened when running this _python ./bbid.py -s "hello world"_:
1. _Access is denied: './bing'_ - fixed with starting cmd as admin, leading to #2 below
2. 99% of downloads FAIL (only 2 files were downloaded, 1 of it was a _*.ashx_ file) - the high fail rate also happens when I ran _python ./bbid.py -s dog_

**Comment by ostrolucky** [comment]
Do you have any more information that could help us figure out the problem? I can't help you with information given unfortunately. Some error messages etc.?

**Comment by Skyferia** [comment]
Strange, now it seems to work.

**_cmd as admin > run python ./bbid.py -s "hello world"_**
The problem was: 
```
FAIL: filename.jpg
FAIL: filename.jpg
FAIL: filename.png
.
.
.
FAIL: filename.jpg
```
I think it's because of the VPN I used to access work. After turning it off, the majority turned to _OK: filename.extension_

Since it's working, I'll stop here. Thanks for the wonderful script, ostrolucky. =)
