### ISSUE TITLE
download more pic

### ISSUE THREAD

**Issue by baiwan9kiwi** [ostrolucky/Bulk-Bing-Image-downloader#30]
i wannna know that how can i download more pic？
everytime i download， only about 130 pics，if i wanna more ，like 500 pics
how can i do？

**Comment by ostrolucky** [comment]
Try increasing this sleep time https://github.com/ostrolucky/Bulk-Bing-Image-downloader/blob/2c0d6d336b72a5e756656d9b48015cbe754399bc/bbid.py#L64

**Comment by baiwan9kiwi** [comment]
thanks i will give a try

**Comment by ostrolucky** [comment]
@baiwan9kiwi Did it help? What value was best for you?

**Comment by baiwan9kiwi** [comment]
yes, it work very well! 
i change the value from 0.1 to 1 
and i download from the website about 400+ pics  per time 
so good!
