### ISSUE TITLE
Cannot Download More Images

### ISSUE THREAD

**Issue by narendrasuthar1** [ostrolucky/Bulk-Bing-Image-downloader#35]
I have follow above Issues, Still I can only Download Images less than 100. I have tried changes in values in time.sleep(50), time.sleep(0.5) many more.

**Comment by ostrolucky** [comment]
did you make sure there are more than 100 images for given keyword?

**Comment by narendrasuthar1** [comment]
yes i have downloaded before 600 images at once myself. with this "time.sleep(50)".
but now unfortunately not working. Maybe Bing changed its algorithm or something, I have no idea. and I want to collect datasets for my model.

**Comment by ostrolucky** [comment]
How can I reproduce the issue?

**Comment by narendrasuthar1** [comment]
Like I don't Know. Maybe I thought you can help me with something, like in your code, we can also apply filters and also same image don't get download twice and all. but now everything is limited now.

**Comment by ostrolucky** [comment]
No, it works for me for random keyword I tried. Don't know why it doesn't work for you. Maybe give me command you are using?

**Comment by narendrasuthar1** [comment]
python New12.py -s "happy expression portrait" -o "Happy Expression Portrait"

**Comment by ostrolucky** [comment]
It downloaded 137 images for e, which is about the same as is on website.

**Comment by narendrasuthar1** [comment]
okay let me try with some other keywords then

**Comment by ostrolucky** [comment]
I guess you were rate limited by bing or something, it works for me. Anyways there isn't anything I can do here, sorry.

**Comment by rickkk856** [comment]
i"m facing the same issue, it only download few images, like, 23

`python bbid.py -s "cat" --limit 2000 -o "cat test"`

![image](https://user-images.githubusercontent.com/62864640/115439694-3e50d680-a1e5-11eb-83f2-e01039f5fd35.png)

if I increase to  time.sleep(0.5) in  [line 88](https://github.com/ostrolucky/Bulk-Bing-Image-downloader/blob/b81824dfb3112bcacec7a3221d4cb2cf1f7a3e91/bbid.py#L88) the code download only 48 images... it means bing might have changed the website structure or something.
