### ISSUE TITLE
adult filter off doesn't work for me

### ISSUE THREAD

**Issue by flaclad** [ostrolucky/Bulk-Bing-Image-downloader#37]
even using the script scrapes just 'safe' images --adult-filter-off

**Comment by ostrolucky** [comment]
Indeed. Bing changed it and disabling it now is not a matter of changing query parameter only. From my initial impression it looks to me we have to open a session with cookies for this to work now

**Comment by flaclad** [comment]
Thank you for replying. Unfortunately I have no idea how to open a session with cookies. any advice?

**Comment by ostrolucky** [comment]
No, you must know how to code in Python to fix this

**Comment by ostrolucky** [comment]
Fixed now
