### ISSUE TITLE
Having the same IP to scrape consistent images

### ISSUE THREAD

**Issue by dlee0324** [ostrolucky/Bulk-Bing-Image-downloader#40]
Thank you for the amazing code -- I'm testing the code and realized that the scraped image results differ from the results if I were to search the keyword directly on the bing website. 

Is there a way to add some parameters in bbid.py so that the image results are consistent with what I'm actually seeing on a website from my IP? 

I reckon this is more of the bing issue, but figured I'd still ask for an advice. Thanks!

**Comment by ostrolucky** [comment]
Probably cookies. This kind of stuff is mostly on you to investigate and patch manually, can't help you much there.
