### ISSUE TITLE
Unpredictable what number of images will be scraped

### ISSUE THREAD

**Issue by bobdewitte** [ostrolucky/Bulk-Bing-Image-downloader#43]
Hi, thanks for your Git repo, awesome tool. However, I'm facing some issues when scraping images. 
If I use same commands, it seems like the number of images that will be downloaded varies every time. Also, with no object I get the number of pictures I want, but only around 500-600 on average when I want 750 images.
For instance, I want to scrape 750 images of 'bulldozers', so I'm using the following command (the filter is because I'm filtering on 'photographs' in Bing): 

`python bbid.py -s "buldozer" -o ./images_photo/bulldozer --limit 750 --filter +filterui:photo-photo&form=IRFLTR&first=1&tsc=ImageBasicHover`

However, it only gives me 355 images.
It varies per object and per execution how many pictures will be returned, do you have an explanation for that? I already tried to play with the 'sleep_time'. I'm using Windows 10 operating system.  
Thanks!

**Comment by ostrolucky** [comment]
Server side issue, sorry. Tool can't give you more images if bing doesn't give it more images.
