### ISSUE TITLE
Using with a CSV file

### ISSUE THREAD

**Issue by henrikf01** [ostrolucky/Bulk-Bing-Image-downloader#44]
I want to use the Bulk Bing Image Downloader to download around 100 images per keyword from a CSV list of 800 keywords. The CSV is structured by the Product #;query_string (E.g. 149;Nespresso Machine).

I tried to add this snippet to the code:

```
def getTitels():
    with open('Coffee.csv') as csvfile:
       Coffee_names = []
       csvrows = csv.reader(csvfile, delimiter=',', quotechar='"')
       for row in csvrows:
           Coffee_names.append(row)
       return Coffee_names
       New_Array = getTitles()
```

Do you have any help regarding this?

Many thanks in advance!

**Comment by ostrolucky** [comment]
BBID can read from the text file, but it expects newline separated list of URLs, that's it. I don't really want to add support for more advanced structures.
