### ISSUE TITLE
--limit combined with txt file with objects

### ISSUE THREAD

**Issue by bobdewitte** [ostrolucky/Bulk-Bing-Image-downloader#45]
Hi,

I trying to download 100 images for a bunch of object classes. I made a txt file 'classes.txt' with several objects on each new line. When I type 'python bbid.py -f classes.txt' in the command line, the code works fine. However, when I type 'python bbid.py -f classes.txt --limit 100', I only get 100 images of the first object in the list, and the code stops after it. I hope you can help me, thanks!

Bob

**Comment by ostrolucky** [comment]
That's intentional behaviour, sorry. Limit is total limit, not limit per keyword.

**Comment by bobdewitte** [comment]
Okay, I understand. Is there not a easy way to work around this?
