### ISSUE TITLE
limited image download

### ISSUE THREAD

**Issue by jothi-prasath** [ostrolucky/Bulk-Bing-Image-downloader#47]
It downloads only limited images around 30

commads i use

> python3 bbid.py "yoga" -o "yoga"
> python3 bbid.py "yoga" -o "yoga" --limit 100

i ran this multiple times
but it downloads only 27 images

![image](https://user-images.githubusercontent.com/64248628/167781963-39c53608-b057-4eb6-8046-fa7f37761926.png)

**Comment by ostrolucky** [comment]
Sorry, that's not a problem of this tool but bing. One of the ways to go around this is eg. using a VPN
